global:
  resolve_timeout: 5m

route:
  receiver: "console"
  routes:
    - match:
        team: "dev"
      receiver: "dev"
    - match:
        team: "infra"
      receiver: "infra"

receivers:
  - name: "console"
  - name: "dev"
  - name: "infra"